/**
 * build-exe.mjs — packages the app into a single self-contained
 * `GymSystem.exe` via Node Single Executable Applications (SEA):
 *
 *   1. runs the normal production build (dist/ + dist-server/index.cjs)
 *   2. embeds dist/ as a base64 map into the server bundle
 *   3. rebuilds the server bundle with the embedded map
 *   4. restores the empty embedded-dist stub
 *   5. injects the bundle into a copy of node.exe (postject)
 *   6. patches the PE subsystem to GUI (no console window)
 *   7. copies the portable node runtime + WhatsApp gateway beside the exe
 *
 * Output: dist-exe/GymSystem.exe  (+ runtime/node.exe, gateway/)
 */
import { build } from "esbuild";
import { execSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
  copyFileSync,
  rmSync,
} from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DIST_DIR = path.join(ROOT, "dist");
const DIST_SERVER = path.join(ROOT, "dist-server", "index.cjs");
const OUT_DIR = path.join(ROOT, "dist-exe");
const EXE_NAME = "GymSystem.exe";
const FUSE = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2";

function log(msg) {
  // eslint-disable-next-line no-console
  console.log(`[build-exe] ${msg}`);
}

function run(cmd, args, opts = {}) {
  const quotedCmd = /[\s]/.test(cmd) ? `"${cmd}"` : cmd;
  try {
    return execSync(quotedCmd + (args.length ? " " + args.map((a) => `"${a}"`).join(" ") : ""), {
      cwd: ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "inherit"],
      ...opts,
    });
  } catch (err) {
    if (err.stdout) log(`stdout: ${String(err.stdout).slice(0, 2000)}`);
    if (err.stderr) log(`stderr: ${String(err.stderr).slice(0, 2000)}`);
    throw err;
  }
}

function walk(dir, base = dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const rel = path.relative(base, full).split(path.sep).join("/");
    if (statSync(full).isDirectory()) {
      if (entry === "node_modules/.bin") continue;
      walk(full, base, acc);
    } else {
      acc.push(rel);
    }
  }
  return acc;
}

const STUB = `/**
 * Frontend dist assets embedded into the packaged EXE (base64, keyed by
 * dist-relative path with forward slashes). scripts/build-exe.mjs briefly
 * fills this map, rebuilds the server bundle, then restores the empty stub so
 * the repo stays small. Normal dev/build runs keep the empty map and serve the
 * real dist/ folder from disk.
 */
export const embeddedDist: Record<string, string> = {};
`;

function embedDist() {
  const files = walk(DIST_DIR);
  const entries = [];
  for (const rel of files) {
    const bytes = readFileSync(path.join(DIST_DIR, rel.split("/").join(path.sep)));
    entries.push(`  ${JSON.stringify(rel)}: ${JSON.stringify(bytes.toString("base64"))},`);
  }
  const header = `/**
 * AUTO-GENERATED by scripts/build-exe.mjs — DO NOT EDIT.
 * Frontend dist assets for the packaged EXE (base64).
 */
export const embeddedDist: Record<string, string> = {
`;
  writeFileSync(path.join(ROOT, "server", "embedded-dist.ts"), header + entries.join("\n") + "\n};\n");
  log(`embedded ${files.length} dist assets (${entries.join("").length} base64 chars)`);
}

function restoreStub() {
  writeFileSync(path.join(ROOT, "server", "embedded-dist.ts"), STUB);
  log("restored embedded-dist stub");
}

function patchGuiSubsystem(exePath) {
  const buf = readFileSync(exePath);
  const e_lfanew = buf.readUInt32LE(0x3c);
  const opt = e_lfanew + 24;
  const magic = buf.readUInt16LE(opt);
  if (magic !== 0x20b) throw new Error(`unexpected PE magic 0x${magic.toString(16)} (not PE32+)`);
  const subsystemOffset = opt + 68;
  const current = buf.readUInt16LE(subsystemOffset);
  buf.writeUInt16LE(2 /* IMAGE_SUBSYSTEM_WINDOWS_GUI */, subsystemOffset);
  writeFileSync(exePath, buf);
  log(`PE subsystem ${current} -> 2 (GUI, no console)`);
}

function buildSea() {
  mkdirSync(OUT_DIR, { recursive: true });

  const blob = path.join(OUT_DIR, "sea-prep.blob");
  const configFile = path.join(OUT_DIR, "sea-config.json");
  writeFileSync(
    configFile,
    JSON.stringify({
      main: "dist-server/index.cjs",
      output: blob,
      disableExperimentalSEAWarning: true,
    }),
  );
  run(process.execPath, ["--experimental-sea-config", configFile]);
  log("sea blob generated");

  const exePath = path.join(OUT_DIR, EXE_NAME);
  copyFileSync(process.execPath, exePath);

  const postjectCli = path.join(ROOT, "node_modules", "postject", "dist", "cli.js");
  if (!existsSync(postjectCli)) throw new Error("postject not installed — run `npm i -D postject`");
  run(process.execPath, [postjectCli, exePath, "NODE_SEA_BLOB", blob, "--sentinel-fuse", FUSE]);
  log("blob injected into GymSystem.exe");

  patchGuiSubsystem(exePath);
  rmSync(blob, { force: true });
  rmSync(configFile, { force: true });
}

function copyRuntime() {
  const runtimeDir = path.join(OUT_DIR, "runtime");
  mkdirSync(runtimeDir, { recursive: true });
  copyFileSync(process.execPath, path.join(runtimeDir, "node.exe"));
  log("portable node runtime copied");

  const gatewaySrc = path.join(ROOT, "whatsapp-gateway");
  if (!existsSync(gatewaySrc)) return;
  const gatewayDst = path.join(OUT_DIR, "gateway");
  mkdirSync(gatewayDst, { recursive: true });
  const only = ["index.js", "http.js", "log.js", "config.js", "numbers.js", "wa-session.js", "wa-send.js", "package.json"];
  for (const rel of walkRestricted(gatewaySrc)) {
    if (only.includes(rel)) copyFileSync(path.join(gatewaySrc, rel), path.join(gatewayDst, rel));
  }
  if (existsSync(path.join(gatewaySrc, "node_modules", "playwright"))) {
    copyTree(path.join(gatewaySrc, "node_modules", "playwright"), path.join(gatewayDst, "node_modules", "playwright"));
    copyTree(path.join(gatewaySrc, "node_modules", "playwright-core"), path.join(gatewayDst, "node_modules", "playwright-core"));
    if (existsSync(path.join(gatewaySrc, "node_modules", ".bin"))) {
      copyTree(path.join(gatewaySrc, "node_modules", ".bin"), path.join(gatewayDst, "node_modules", ".bin"));
    }
    log("playwright runtime copied (messaging ready)");
  } else {
    log("WARNING: gateway node_modules missing — run `npm run setup-whatsapp-gateway` first");
  }
}

function walkRestricted(dir, base = dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const rel = path.relative(base, full).split(path.sep).join("/");
    if (entry === "node_modules" || entry === "wa-profile") continue;
    if (statSync(full).isDirectory()) walkRestricted(full, base, acc);
    else acc.push(rel);
  }
  return acc;
}

function copyTree(src, dst) {
  for (const entry of readdirSync(src)) {
    const s = path.join(src, entry);
    const d = path.join(dst, entry);
    if (statSync(s).isDirectory()) {
      mkdirSync(d, { recursive: true });
      copyTree(s, d);
    } else {
      mkdirSync(path.dirname(d), { recursive: true });
      copyFileSync(s, d);
    }
  }
}

function main() {
  log("step 1/6: production build");
  run("npm", ["run", "build"]);

  if (!existsSync(DIST_DIR)) throw new Error("dist/ missing after build");
  log("step 2/6: embedding dist into the server bundle");
  embedDist();
  try {
    log("step 3/6: rebuilding server bundle with embedded assets");
    run(process.execPath, [path.join(ROOT, "scripts", "build-server.mjs")]);
  } finally {
    restoreStub();
  }

  log("step 4/6: SEA build + postject + GUI subsystem");
  buildSea();

  log("step 5/6: copying runtime + gateway");
  copyRuntime();

  log("step 6/6: done");
  log(`→ ${path.join(OUT_DIR, EXE_NAME)}`);
  if (existsSync(path.join(OUT_DIR, "runtime", "node.exe"))) {
    log(`→ ${path.join(OUT_DIR, "runtime", "node.exe")} (portable node)`);
  }
  if (existsSync(path.join(OUT_DIR, "gateway", "index.js"))) {
    log(`→ ${path.join(OUT_DIR, "gateway")} (WhatsApp gateway)`);
  }
}

main();